# Generated by Django 5.0.5 on 2024-05-07 23:26

import recipes.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(storage=recipes.storage.OverwriteStorage(), upload_to='recipes'),
        ),
    ]
